### ISSUE TITLE
Recherche : Fonctionnalités du raspberry

### ISSUE THREAD

**Issue by Ventouz** [Ventouz/Workshop#1]

**Comment by Ventouz** [comment]
- capteur audio
- capteur IF

**Comment by Ventouz** [comment]
Le capteur de bruit se fait en ON/OFF.
On peut régler le seuil.

**Comment by Nivzerrr** [comment]
Spécificités de notre Raspberry : 
- Quad Core 1.2GHz Broadcom BCM2837 64bit CPU
- 1GB RAM
- BCM43438 wireless LAN and Bluetooth Low Energy (BLE) on board
- 100 Base Ethernet
- 40-pin extended GPIO
- 4 USB 2 ports
- 4 Pole stereo output and composite video port
- Full size HDMI
- CSI camera port for connecting a Raspberry Pi camera
- DSI display port for connecting a Raspberry Pi touchscreen display
- Micro SD port for loading your operating system and storing data
- Upgraded switched Micro USB power source up to 2.5A
