### ISSUE TITLE
Remise à zéro de la config

### ISSUE THREAD

**Issue by Ventouz** [Ventouz/Workshop#17]

**Comment by BabyReggae** [comment]
<?php

    /* DEBUT D'INITIALISATION DE LA CONNEXION DB */
    try
    {
        $bdd = new PDO('mysql:host=localhost;dbname=berceuse', "root", "");
        $bdd->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_OBJ);
    }
    catch(PDOException $e)
    {
        echo "Impossible de se connecter";
        die();
    }

$req = 'INSERT INTO enfant (nom, prenom)
        VALUES ("caca", "cucu")';
        $insertUsr = $bdd->query($req);
?>

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-06-27 13:45 GMT+02:00 Ventouz <notifications@github.com>:
